cmake_minimum_required(VERSION 3.22)
if(NOT TEST_DIR MATCHES "/sdk-[a-z-]+$")
  message(FATAL_ERROR "SDK tests must use their own build directory")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/api" "${TEST_DIR}/payload/sdk/lib/cmake/Ultralight")
file(WRITE "${TEST_DIR}/payload/sdk/lib/cmake/Ultralight/UltralightConfig.cmake" "# test package\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${TEST_DIR}/package.zip" --format=zip sdk
  WORKING_DIRECTORY "${TEST_DIR}/payload" COMMAND_ERROR_IS_FATAL ANY)
file(SHA256 "${TEST_DIR}/package.zip" _sha256)
set(_version "2.0.0-beta.2")
set(_url "file://${TEST_DIR}/package.zip")
if(CASE STREQUAL "checksum")
  string(REPEAT "0" 64 _sha256)
elseif(CASE STREQUAL "old-version")
  set(_version "1.4.0")
elseif(CASE STREQUAL "download-error")
  set(_url "file://${TEST_DIR}/missing.zip")
endif()
file(WRITE "${TEST_DIR}/api/download"
  "{\"version\":\"${_version}\",\"platform\":\"linux-x64\",\"filename\":\"sdk.7z\",\"sha256\":\"${_sha256}\",\"url\":\"${_url}\"}")

function(run_driver expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_DIR=${SOURCE_DIR}" "-DTEST_DIR=${TEST_DIR}"
    "-DULTRALIGHT_SDK_API_URL=file://${TEST_DIR}/api" "-DMODE=${CASE}"
    -P "${SOURCE_DIR}/tests/sdk_driver.cmake"
    RESULT_VARIABLE _exit OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
  if(expected STREQUAL "success")
    if(NOT _exit EQUAL 0)
      message(FATAL_ERROR "SDK fixture failed: ${_stdout}\n${_stderr}")
    endif()
  else()
    string(FIND "${_stderr}" "${expected}" _found)
    if(_exit EQUAL 0 OR _found EQUAL -1)
      message(FATAL_ERROR "Expected '${expected}', got ${_exit}: ${_stdout}\n${_stderr}")
    endif()
  endif()
endfunction()

if(CASE STREQUAL "cache" OR CASE STREQUAL "cached-checksum")
  run_driver(success)
  if(CASE STREQUAL "cache")
    file(REMOVE "${TEST_DIR}/package.zip")
    run_driver(success)
  else()
    file(GLOB _archives "${TEST_DIR}/cache/*/sdk.7z")
    list(GET _archives 0 _archive)
    file(APPEND "${_archive}" "corrupt")
    run_driver("Cached SDK SHA-256 mismatch")
  endif()
elseif(CASE STREQUAL "checksum")
  run_driver("SDK SHA-256 mismatch")
elseif(CASE STREQUAL "old-version")
  run_driver("ulbind17 requires an Ultralight 2.x SDK")
elseif(CASE STREQUAL "platform")
  run_driver("SDK is not supported on Darwin/x86_64")
elseif(CASE STREQUAL "download-error")
  run_driver("SDK download failed")
else()
  message(FATAL_ERROR "Unknown SDK test case: ${CASE}")
endif()
