cmake_minimum_required(VERSION 3.22)
include("${SOURCE_DIR}/ultralight-sdk/SDK.cmake")
if(MODE STREQUAL "platform")
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CMAKE_SYSTEM_PROCESSOR x86_64)
  ulbind17_sdk_platform(_platform)
else()
  ulbind17_download_sdk(_root linux-x64 latest "${TEST_DIR}/cache")
  if(NOT EXISTS "${_root}/lib/cmake/Ultralight/UltralightConfig.cmake")
    message(FATAL_ERROR "Extracted SDK root is incorrect")
  endif()
endif()
