function(ulbind17_sdk_platform output)
  set(_arch "${CMAKE_SYSTEM_PROCESSOR}")
  if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    set(_arch "${CMAKE_OSX_ARCHITECTURES}")
  endif()
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND _arch MATCHES "^(arm64|aarch64)$")
    set(_platform "macos-arm64")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND _arch MATCHES "^(x86_64|amd64|AMD64)$")
    set(_platform "linux-x64")
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows" AND _arch MATCHES "^(x86_64|amd64|AMD64)$"
      AND CMAKE_SIZEOF_VOID_P EQUAL 8 AND NOT CMAKE_GENERATOR_PLATFORM MATCHES "^(ARM64|Win32)$")
    set(_platform "windows-x64")
  else()
    message(FATAL_ERROR "Ultralight 2.x SDK is not supported on ${CMAKE_SYSTEM_NAME}/${_arch}")
  endif()
  set(${output} "${_platform}" PARENT_SCOPE)
endfunction()

function(ulbind17_download_sdk output platform version cache_dir)
  if(NOT version MATCHES "^(latest|[0-9]+\\.[0-9]+\\.[0-9]+(-[A-Za-z0-9.]+)?)$")
    message(FATAL_ERROR "Invalid ULTRALIGHT_SDK_VERSION: ${version}")
  endif()
  file(MAKE_DIRECTORY "${cache_dir}")
  file(DOWNLOAD
    "${ULTRALIGHT_SDK_API_URL}/download?platform=${platform}&version=${version}&format=json"
    "${cache_dir}/metadata.json" STATUS _status TLS_VERIFY ON TIMEOUT 60)
  list(GET _status 0 _status_code)
  if(NOT _status_code EQUAL 0)
    message(FATAL_ERROR "SDK metadata download failed: ${_status}")
  endif()
  file(READ "${cache_dir}/metadata.json" _metadata)
  foreach(_field IN ITEMS version platform filename sha256 url)
    string(JSON _${_field} ERROR_VARIABLE _error GET "${_metadata}" ${_field})
    if(_error OR NOT _${_field})
      message(FATAL_ERROR "SDK metadata is missing a valid ${_field}")
    endif()
  endforeach()
  if(NOT _version MATCHES "^2\\.[0-9]+\\.[0-9]+(-[A-Za-z0-9.]+)?$")
    message(FATAL_ERROR "ulbind17 requires an Ultralight 2.x SDK; download API returned ${_version}")
  endif()
  if(NOT _platform STREQUAL platform OR (NOT version STREQUAL "latest" AND NOT _version STREQUAL version))
    message(FATAL_ERROR "SDK metadata does not match the requested platform/version")
  endif()
  string(LENGTH "${_sha256}" _hash_length)
  if(NOT _hash_length EQUAL 64 OR NOT _sha256 MATCHES "^[A-Fa-f0-9]+$")
    message(FATAL_ERROR "SDK metadata has an invalid SHA-256")
  endif()
  string(TOLOWER "${_sha256}" _sha256)
  # Never use the API's filename as a local path.
  set(_entry "${cache_dir}/${_version}-${platform}-${_sha256}")
  file(MAKE_DIRECTORY "${_entry}")
  set(_archive "${_entry}/sdk.7z")
  if(EXISTS "${_archive}")
    file(SHA256 "${_archive}" _actual_hash)
    if(NOT _actual_hash STREQUAL _sha256)
      message(FATAL_ERROR "Cached SDK SHA-256 mismatch: ${_archive}")
    endif()
  else()
    file(DOWNLOAD "${_url}" "${_archive}" STATUS _status TLS_VERIFY ON SHOW_PROGRESS TIMEOUT 300)
    list(GET _status 0 _status_code)
    if(NOT _status_code EQUAL 0)
      file(REMOVE "${_archive}")
      message(FATAL_ERROR "SDK download failed: ${_status}")
    endif()
    file(SHA256 "${_archive}" _actual_hash)
    if(NOT _actual_hash STREQUAL _sha256)
      file(REMOVE "${_archive}")
      message(FATAL_ERROR "SDK SHA-256 mismatch")
    endif()
  endif()
  set(_root "${_entry}/sdk")
  if(NOT EXISTS "${_entry}/extracted")
    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${_root}")
    file(WRITE "${_entry}/extracted" "${_sha256}\n")
  endif()
  # SDK releases may have a containing directory in the archive.
  if(NOT EXISTS "${_root}/lib/cmake/Ultralight/UltralightConfig.cmake")
    file(GLOB _configs "${_root}/*/lib/cmake/Ultralight/UltralightConfig.cmake")
    list(LENGTH _configs _count)
    if(NOT _count EQUAL 1)
      message(FATAL_ERROR "Downloaded SDK does not contain a CMake package")
    endif()
    list(GET _configs 0 _config)
    get_filename_component(_config_directory "${_config}" DIRECTORY)
    get_filename_component(_root "${_config_directory}/../../.." ABSOLUTE)
  endif()
  set(${output} "${_root}" PARENT_SCOPE)
endfunction()
